version: '3.8'
services:
  eureka:
    build: ./eureka
    ports:
      - "8761:8761"
    networks:
      - art-network

  apigateway:
    build: ./apigateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka
    networks:
      - art-network

  authservice:
    build: ./authservice
    depends_on:
      - eureka
    networks:
      - art-network

  artservice:
    build: ./artservice
    depends_on:
      - eureka
    networks:
      - art-network

  cartservice:
    build: ./cartservice
    depends_on:
      - eureka
    networks:
      - art-network

networks:
  art-network:
